# Generated by Django 5.1.7 on 2025-04-07 19:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftlog',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='shiftlog',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='shiftroster',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='shiftroster',
            name='shift',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='leave_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='leave',
            name='applied_on',
            field=models.DateField(auto_now_add=True, default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('SICK', 'Sick Leave'), ('VACATION', 'Vacation'), ('CASUAL', 'Casual Leave'), ('EMERGENCY', 'Emergency Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(default='No Reason Provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshifts',
            name='shift_type',
            field=models.CharField(choices=[('Morning', 'Morning Shift'), ('Night', 'Night Shift'), ('Evening', 'Evening Shift'), ('Graveyard', 'Graveyard Shift')], max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.leave')),
            ],
        ),
        migrations.DeleteModel(
            name='Overtime',
        ),
        migrations.DeleteModel(
            name='ShiftLog',
        ),
        migrations.DeleteModel(
            name='ShiftRoster',
        ),
    ]
