# Generated by Django 5.1.7 on 2025-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='temp_field',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
