# Generated by Django 5.1.7 on 2025-03-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='temp_field',
        ),
    ]
