# Generated by Django 5.1.7 on 2025-03-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('SE', 'Software Engineer'), ('SSE', 'Senior Software Engineer'), ('TL', 'Team Lead'), ('PM', 'Project Manager'), ('HR', 'HR Manager'), ('DA', 'Data Analyst'), ('DS', 'Data Scientist'), ('DEV', 'Developer')], max_length=50),
        ),
    ]
