# Generated by Django 5.1.7 on 2025-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_options_alter_employeeprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=11),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
