# Generated by Django 5.1.7 on 2025-04-01 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0007_alter_employee_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_type', models.CharField(choices=[('Resignation', 'Resignation'), ('Termination', 'Termination'), ('Retirement', 'Retirement'), ('Other', 'Other')], max_length=20)),
                ('exit_date', models.DateField()),
                ('last_working_day', models.DateField()),
                ('exit_interview_conducted', models.BooleanField(default=False)),
                ('exit_reason', models.TextField(blank=True, null=True)),
                ('assets_returned', models.BooleanField(default=False)),
                ('clearance_completed', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Exit',
                'verbose_name_plural': 'Employee Exits',
            },
        ),
    ]
