# Generated by Django 5.1.7 on 2025-03-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('SALES', 'Sales'), ('PROD', 'Production')], max_length=50)),
                ('location', models.CharField(max_length=75)),
            ],
        ),
    ]
